name: "Input/Context Flow Demonstrator"
description: "Demonstrates common unsafe dataflow patterns from inputs and workflow context into commands, env, and outputs."
author: "YOUR_ORG_OR_NAME"
branding:
  icon: "alert-triangle"
  color: "red"

inputs:
  user_text:
    description: "Untrusted user-supplied text (for testing dataflow detection)"
    required: true

outputs:
  arg_output:
    description: "Echo of user input (Arg -> Output)"
    value: ${{ steps.arg_to_output.outputs.arg_output }}
  ctx_output:
    description: "Echo of context value (Context -> Output)"
    value: ${{ steps.ctx_to_output.outputs.ctx_output }}

runs:
  using: "composite"
  steps:
    # 1) Arg -> Sink
    - id: arg_to_sink
      shell: bash
      run: |
        # Unsafe shape: input flows into a command string (sink).
        # Benign: only prints.
        bash -lc "echo 'ARG_TO_SINK:' '${{ inputs.user_text }}'"

    # 2) Context -> Sink
    - id: ctx_to_sink
      shell: bash
      run: |
        # Unsafe shape: context flows into a command string (sink).
        bash -lc "echo 'CTX_TO_SINK:' '${{ github.actor }}' '${{ github.ref }}'"

    # 3) Arg -> Env
    - id: arg_to_env
      shell: bash
      run: |
        # Unsafe shape: raw input exported to environment.
        echo "UNSAFE_ARG_ENV=${{ inputs.user_text }}" >> "$GITHUB_ENV"

    # 4) Context -> Env
    - id: ctx_to_env
      shell: bash
      run: |
        # Unsafe shape: context exported to environment.
        echo "UNSAFE_CTX_ENV=${{ github.repository }}:${{ github.sha }}" >> "$GITHUB_ENV"

    # 5) Arg -> Output
    - id: arg_to_output
      shell: bash
      run: |
        # Unsafe shape: raw input written to outputs.
        echo "arg_output=${{ inputs.user_text }}" >> "$GITHUB_OUTPUT"

    # 6) Context -> Output
    - id: ctx_to_output
      shell: bash
      run: |
        # Unsafe shape: context written to outputs.
        echo "ctx_output=${{ github.actor }}@${{ github.ref }}" >> "$GITHUB_OUTPUT"